//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsAgileSoapApi4.SmsAgileSoapService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutenticacaoDTO", Namespace="http://schemas.datacontract.org/2004/07/SmsGateway.Application.CoreContext.DTO.SM" +
        "SModule")]
    [System.SerializableAttribute()]
    public partial class AutenticacaoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MensagemDTO", Namespace="http://schemas.datacontract.org/2004/07/SmsGateway.Application.CoreContext.DTO.SM" +
        "SModule")]
    [System.SerializableAttribute()]
    public partial class MensagemDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ContratoDaOperadoraIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ContratoDoClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataDeEnvioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataDeRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataDoUltimoUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroDoDestinatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroDoRemetenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid StatusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusMensagemAoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusQuantoDebitarDoContratoDoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoDaMensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ContratoDaOperadoraId {
            get {
                return this.ContratoDaOperadoraIdField;
            }
            set {
                if ((this.ContratoDaOperadoraIdField.Equals(value) != true)) {
                    this.ContratoDaOperadoraIdField = value;
                    this.RaisePropertyChanged("ContratoDaOperadoraId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ContratoDoClienteId {
            get {
                return this.ContratoDoClienteIdField;
            }
            set {
                if ((this.ContratoDoClienteIdField.Equals(value) != true)) {
                    this.ContratoDoClienteIdField = value;
                    this.RaisePropertyChanged("ContratoDoClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataDeEnvio {
            get {
                return this.DataDeEnvioField;
            }
            set {
                if ((this.DataDeEnvioField.Equals(value) != true)) {
                    this.DataDeEnvioField = value;
                    this.RaisePropertyChanged("DataDeEnvio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataDeRegistro {
            get {
                return this.DataDeRegistroField;
            }
            set {
                if ((this.DataDeRegistroField.Equals(value) != true)) {
                    this.DataDeRegistroField = value;
                    this.RaisePropertyChanged("DataDeRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataDoUltimoUpdate {
            get {
                return this.DataDoUltimoUpdateField;
            }
            set {
                if ((this.DataDoUltimoUpdateField.Equals(value) != true)) {
                    this.DataDoUltimoUpdateField = value;
                    this.RaisePropertyChanged("DataDoUltimoUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEnabled {
            get {
                return this.IsEnabledField;
            }
            set {
                if ((this.IsEnabledField.Equals(value) != true)) {
                    this.IsEnabledField = value;
                    this.RaisePropertyChanged("IsEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDoDestinatario {
            get {
                return this.NumeroDoDestinatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroDoDestinatarioField, value) != true)) {
                    this.NumeroDoDestinatarioField = value;
                    this.RaisePropertyChanged("NumeroDoDestinatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDoRemetente {
            get {
                return this.NumeroDoRemetenteField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroDoRemetenteField, value) != true)) {
                    this.NumeroDoRemetenteField = value;
                    this.RaisePropertyChanged("NumeroDoRemetente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusCodigo {
            get {
                return this.StatusCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodigoField, value) != true)) {
                    this.StatusCodigoField = value;
                    this.RaisePropertyChanged("StatusCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid StatusId {
            get {
                return this.StatusIdField;
            }
            set {
                if ((this.StatusIdField.Equals(value) != true)) {
                    this.StatusIdField = value;
                    this.RaisePropertyChanged("StatusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusMensagemAoCliente {
            get {
                return this.StatusMensagemAoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusMensagemAoClienteField, value) != true)) {
                    this.StatusMensagemAoClienteField = value;
                    this.RaisePropertyChanged("StatusMensagemAoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusQuantoDebitarDoContratoDoCliente {
            get {
                return this.StatusQuantoDebitarDoContratoDoClienteField;
            }
            set {
                if ((this.StatusQuantoDebitarDoContratoDoClienteField.Equals(value) != true)) {
                    this.StatusQuantoDebitarDoContratoDoClienteField = value;
                    this.RaisePropertyChanged("StatusQuantoDebitarDoContratoDoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextoDaMensagem {
            get {
                return this.TextoDaMensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoDaMensagemField, value) != true)) {
                    this.TextoDaMensagemField = value;
                    this.RaisePropertyChanged("TextoDaMensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContatoDTO", Namespace="http://schemas.datacontract.org/2004/07/SmsGateway.Application.CoreContext.DTO.SM" +
        "SModule")]
    [System.SerializableAttribute()]
    public partial class ContatoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NumeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEnabled {
            get {
                return this.IsEnabledField;
            }
            set {
                if ((this.IsEnabledField.Equals(value) != true)) {
                    this.IsEnabledField = value;
                    this.RaisePropertyChanged("IsEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaDeContatosDTO", Namespace="http://schemas.datacontract.org/2004/07/SmsGateway.Application.CoreContext.DTO.SM" +
        "SModule")]
    [System.SerializableAttribute()]
    public partial class ListaDeContatosDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SmsAgileSoapApi4.SmsAgileSoapService.ContatoDTO[] ContatosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SmsAgileSoapApi4.SmsAgileSoapService.ContatoDTO[] Contatos {
            get {
                return this.ContatosField;
            }
            set {
                if ((object.ReferenceEquals(this.ContatosField, value) != true)) {
                    this.ContatosField = value;
                    this.RaisePropertyChanged("Contatos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEnabled {
            get {
                return this.IsEnabledField;
            }
            set {
                if ((this.IsEnabledField.Equals(value) != true)) {
                    this.IsEnabledField = value;
                    this.RaisePropertyChanged("IsEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsAgileSoapService.IApiService")]
    public interface IApiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/GetSaldoDeMensagens", ReplyAction="http://tempuri.org/IApiService/GetSaldoDeMensagensResponse")]
        int GetSaldoDeMensagens(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/GetMensagensEnviadas", ReplyAction="http://tempuri.org/IApiService/GetMensagensEnviadasResponse")]
        SmsAgileSoapApi4.SmsAgileSoapService.MensagemDTO[] GetMensagensEnviadas(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/GetMensagem", ReplyAction="http://tempuri.org/IApiService/GetMensagemResponse")]
        SmsAgileSoapApi4.SmsAgileSoapService.MensagemDTO GetMensagem(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, string idMensagem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/EnviarMensagem", ReplyAction="http://tempuri.org/IApiService/EnviarMensagemResponse")]
        SmsAgileSoapApi4.SmsAgileSoapService.MensagemDTO EnviarMensagem(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, SmsAgileSoapApi4.SmsAgileSoapService.MensagemDTO mensagem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/EnviarMensagemStringRemetente", ReplyAction="http://tempuri.org/IApiService/EnviarMensagemStringRemetenteResponse")]
        SmsAgileSoapApi4.SmsAgileSoapService.MensagemDTO EnviarMensagemStringRemetente(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, string destinatario, string remetente, string texto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/EnviarMensagemString", ReplyAction="http://tempuri.org/IApiService/EnviarMensagemStringResponse")]
        SmsAgileSoapApi4.SmsAgileSoapService.MensagemDTO EnviarMensagemString(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, string destinatario, string texto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/AdicionarContato", ReplyAction="http://tempuri.org/IApiService/AdicionarContatoResponse")]
        SmsAgileSoapApi4.SmsAgileSoapService.ContatoDTO AdicionarContato(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, SmsAgileSoapApi4.SmsAgileSoapService.ContatoDTO contato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/AtualizarContato", ReplyAction="http://tempuri.org/IApiService/AtualizarContatoResponse")]
        void AtualizarContato(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, SmsAgileSoapApi4.SmsAgileSoapService.ContatoDTO contato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/RemoverContato", ReplyAction="http://tempuri.org/IApiService/RemoverContatoResponse")]
        void RemoverContato(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, System.Guid contatoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/EnviarMensagemParaContatos", ReplyAction="http://tempuri.org/IApiService/EnviarMensagemParaContatosResponse")]
        SmsAgileSoapApi4.SmsAgileSoapService.MensagemDTO[] EnviarMensagemParaContatos(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, string texto, string remetente, SmsAgileSoapApi4.SmsAgileSoapService.ContatoDTO[] contatos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/Contato", ReplyAction="http://tempuri.org/IApiService/ContatoResponse")]
        SmsAgileSoapApi4.SmsAgileSoapService.ContatoDTO Contato(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, System.Guid contatoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/TodosOsContatos", ReplyAction="http://tempuri.org/IApiService/TodosOsContatosResponse")]
        SmsAgileSoapApi4.SmsAgileSoapService.ContatoDTO[] TodosOsContatos(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/GetListaDeContatos", ReplyAction="http://tempuri.org/IApiService/GetListaDeContatosResponse")]
        SmsAgileSoapApi4.SmsAgileSoapService.ListaDeContatosDTO GetListaDeContatos(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/ListListasDeContatos", ReplyAction="http://tempuri.org/IApiService/ListListasDeContatosResponse")]
        SmsAgileSoapApi4.SmsAgileSoapService.ListaDeContatosDTO[] ListListasDeContatos(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/CreateListaDeContatos", ReplyAction="http://tempuri.org/IApiService/CreateListaDeContatosResponse")]
        SmsAgileSoapApi4.SmsAgileSoapService.ListaDeContatosDTO CreateListaDeContatos(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, SmsAgileSoapApi4.SmsAgileSoapService.ListaDeContatosDTO dtoInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/UpdateListaDeContatos", ReplyAction="http://tempuri.org/IApiService/UpdateListaDeContatosResponse")]
        void UpdateListaDeContatos(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, SmsAgileSoapApi4.SmsAgileSoapService.ListaDeContatosDTO dtoInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/DisableListaDeContatos", ReplyAction="http://tempuri.org/IApiService/DisableListaDeContatosResponse")]
        void DisableListaDeContatos(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, SmsAgileSoapApi4.SmsAgileSoapService.ListaDeContatosDTO dtoInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiService/EnviarMensagemParaListaDeContatos", ReplyAction="http://tempuri.org/IApiService/EnviarMensagemParaListaDeContatosResponse")]
        SmsAgileSoapApi4.SmsAgileSoapService.MensagemDTO[] EnviarMensagemParaListaDeContatos(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, string texto, string remetente, SmsAgileSoapApi4.SmsAgileSoapService.ListaDeContatosDTO dtoInstance);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IApiServiceChannel : SmsAgileSoapApi4.SmsAgileSoapService.IApiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApiServiceClient : System.ServiceModel.ClientBase<SmsAgileSoapApi4.SmsAgileSoapService.IApiService>, SmsAgileSoapApi4.SmsAgileSoapService.IApiService {
        
        public ApiServiceClient() {
        }
        
        public ApiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetSaldoDeMensagens(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao) {
            return base.Channel.GetSaldoDeMensagens(autenticacao);
        }
        
        public SmsAgileSoapApi4.SmsAgileSoapService.MensagemDTO[] GetMensagensEnviadas(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao) {
            return base.Channel.GetMensagensEnviadas(autenticacao);
        }
        
        public SmsAgileSoapApi4.SmsAgileSoapService.MensagemDTO GetMensagem(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, string idMensagem) {
            return base.Channel.GetMensagem(autenticacao, idMensagem);
        }
        
        public SmsAgileSoapApi4.SmsAgileSoapService.MensagemDTO EnviarMensagem(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, SmsAgileSoapApi4.SmsAgileSoapService.MensagemDTO mensagem) {
            return base.Channel.EnviarMensagem(autenticacao, mensagem);
        }
        
        public SmsAgileSoapApi4.SmsAgileSoapService.MensagemDTO EnviarMensagemStringRemetente(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, string destinatario, string remetente, string texto) {
            return base.Channel.EnviarMensagemStringRemetente(autenticacao, destinatario, remetente, texto);
        }
        
        public SmsAgileSoapApi4.SmsAgileSoapService.MensagemDTO EnviarMensagemString(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, string destinatario, string texto) {
            return base.Channel.EnviarMensagemString(autenticacao, destinatario, texto);
        }
        
        public SmsAgileSoapApi4.SmsAgileSoapService.ContatoDTO AdicionarContato(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, SmsAgileSoapApi4.SmsAgileSoapService.ContatoDTO contato) {
            return base.Channel.AdicionarContato(autenticacao, contato);
        }
        
        public void AtualizarContato(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, SmsAgileSoapApi4.SmsAgileSoapService.ContatoDTO contato) {
            base.Channel.AtualizarContato(autenticacao, contato);
        }
        
        public void RemoverContato(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, System.Guid contatoId) {
            base.Channel.RemoverContato(autenticacao, contatoId);
        }
        
        public SmsAgileSoapApi4.SmsAgileSoapService.MensagemDTO[] EnviarMensagemParaContatos(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, string texto, string remetente, SmsAgileSoapApi4.SmsAgileSoapService.ContatoDTO[] contatos) {
            return base.Channel.EnviarMensagemParaContatos(autenticacao, texto, remetente, contatos);
        }
        
        public SmsAgileSoapApi4.SmsAgileSoapService.ContatoDTO Contato(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, System.Guid contatoId) {
            return base.Channel.Contato(autenticacao, contatoId);
        }
        
        public SmsAgileSoapApi4.SmsAgileSoapService.ContatoDTO[] TodosOsContatos(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao) {
            return base.Channel.TodosOsContatos(autenticacao);
        }
        
        public SmsAgileSoapApi4.SmsAgileSoapService.ListaDeContatosDTO GetListaDeContatos(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, string id) {
            return base.Channel.GetListaDeContatos(autenticacao, id);
        }
        
        public SmsAgileSoapApi4.SmsAgileSoapService.ListaDeContatosDTO[] ListListasDeContatos(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao) {
            return base.Channel.ListListasDeContatos(autenticacao);
        }
        
        public SmsAgileSoapApi4.SmsAgileSoapService.ListaDeContatosDTO CreateListaDeContatos(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, SmsAgileSoapApi4.SmsAgileSoapService.ListaDeContatosDTO dtoInstance) {
            return base.Channel.CreateListaDeContatos(autenticacao, dtoInstance);
        }
        
        public void UpdateListaDeContatos(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, SmsAgileSoapApi4.SmsAgileSoapService.ListaDeContatosDTO dtoInstance) {
            base.Channel.UpdateListaDeContatos(autenticacao, dtoInstance);
        }
        
        public void DisableListaDeContatos(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, SmsAgileSoapApi4.SmsAgileSoapService.ListaDeContatosDTO dtoInstance) {
            base.Channel.DisableListaDeContatos(autenticacao, dtoInstance);
        }
        
        public SmsAgileSoapApi4.SmsAgileSoapService.MensagemDTO[] EnviarMensagemParaListaDeContatos(SmsAgileSoapApi4.SmsAgileSoapService.AutenticacaoDTO autenticacao, string texto, string remetente, SmsAgileSoapApi4.SmsAgileSoapService.ListaDeContatosDTO dtoInstance) {
            return base.Channel.EnviarMensagemParaListaDeContatos(autenticacao, texto, remetente, dtoInstance);
        }
    }
}
