//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsGateway.Application.CoreContext.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmsGateway.Application.CoreContext.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid client contract, cant send message..
        /// </summary>
        internal static string error_InvalidClientContract {
            get {
                return ResourceManager.GetString("error_InvalidClientContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: Could Not Find Client Contract.
        /// </summary>
        internal static string exception_CouldNotFindClientContract {
            get {
                return ResourceManager.GetString("exception_CouldNotFindClientContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comtele.
        /// </summary>
        internal static string operadoraApi_Comtele {
            get {
                return ResourceManager.GetString("operadoraApi_Comtele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HumanSms.
        /// </summary>
        internal static string operadoraApi_HumanSms {
            get {
                return ResourceManager.GetString("operadoraApi_HumanSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null.
        /// </summary>
        internal static string operadoraApi_Null {
            get {
                return ResourceManager.GetString("operadoraApi_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tww.
        /// </summary>
        internal static string operadoraApi_Tww {
            get {
                return ResourceManager.GetString("operadoraApi_Tww", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Add Administrator With Empty Information.
        /// </summary>
        internal static string warning_CannotAddAdminWithEmptyInformation {
            get {
                return ResourceManager.GetString("warning_CannotAddAdminWithEmptyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Add Client With Empty Information.
        /// </summary>
        internal static string warning_CannotAddClientWithEmptyInformation {
            get {
                return ResourceManager.GetString("warning_CannotAddClientWithEmptyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Add Contract With Empty Information.
        /// </summary>
        internal static string warning_CannotAddContractWithEmptyInformation {
            get {
                return ResourceManager.GetString("warning_CannotAddContractWithEmptyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Add Message With Empty Information.
        /// </summary>
        internal static string warning_CannotAddMessageWithEmptyInformation {
            get {
                return ResourceManager.GetString("warning_CannotAddMessageWithEmptyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Remove Non Existing Administrator.
        /// </summary>
        internal static string warning_CannotRemoveNonExistingAdmin {
            get {
                return ResourceManager.GetString("warning_CannotRemoveNonExistingAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Arguments.
        /// </summary>
        internal static string warning_InvalidArguments {
            get {
                return ResourceManager.GetString("warning_InvalidArguments", resourceCulture);
            }
        }
    }
}
