//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsGateway.Presentation.Seedwork.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmsGateway.Presentation.Seedwork.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        public static string Adicionar {
            get {
                return ResourceManager.GetString("Adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Contato.
        /// </summary>
        public static string AdicionarContato {
            get {
                return ResourceManager.GetString("AdicionarContato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Lista.
        /// </summary>
        public static string AdicionarLista {
            get {
                return ResourceManager.GetString("AdicionarLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Mensagem.
        /// </summary>
        public static string AdicionarMensagem {
            get {
                return ResourceManager.GetString("AdicionarMensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assunto.
        /// </summary>
        public static string Assunto {
            get {
                return ResourceManager.GetString("Assunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastre contatos para poder enviar mensagens..
        /// </summary>
        public static string CadastreContatosParaEnviarMensagens {
            get {
                return ResourceManager.GetString("CadastreContatosParaEnviarMensagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo confirmação está diferente da nova senha..
        /// </summary>
        public static string ConfirmacaoSenhaErrada {
            get {
                return ResourceManager.GetString("ConfirmacaoSenhaErrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação da nova Senha.
        /// </summary>
        public static string ConfirmaSenha {
            get {
                return ResourceManager.GetString("ConfirmaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato.
        /// </summary>
        public static string Contato {
            get {
                return ResourceManager.GetString("Contato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contatos da Lista.
        /// </summary>
        public static string ContatosDaLista {
            get {
                return ResourceManager.GetString("ContatosDaLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contatos fora da Lista.
        /// </summary>
        public static string ContatosForaDaLista {
            get {
                return ResourceManager.GetString("ContatosForaDaLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Expiração.
        /// </summary>
        public static string DataExpiracao {
            get {
                return ResourceManager.GetString("DataExpiracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinatário.
        /// </summary>
        public static string Destinatario {
            get {
                return ResourceManager.GetString("Destinatario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string Enviar {
            get {
                return ResourceManager.GetString("Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar Mensagem.
        /// </summary>
        public static string EnviarMensagem {
            get {
                return ResourceManager.GetString("EnviarMensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar mensagem para um contato.
        /// </summary>
        public static string EnviarMensagemParaContato {
            get {
                return ResourceManager.GetString("EnviarMensagemParaContato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar mensagem para uma lista.
        /// </summary>
        public static string EnviarMensagemParaLista {
            get {
                return ResourceManager.GetString("EnviarMensagemParaLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string Excluir {
            get {
                return ResourceManager.GetString("Excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja exluir este contato?.
        /// </summary>
        public static string ExcluirContato {
            get {
                return ResourceManager.GetString("ExcluirContato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja exluir esta lista?.
        /// </summary>
        public static string ExcluirListaDeContatos {
            get {
                return ResourceManager.GetString("ExcluirListaDeContatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Houve um erro inesperado..
        /// </summary>
        public static string GeneralException {
            get {
                return ResourceManager.GetString("GeneralException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        public static string Identificador {
            get {
                return ResourceManager.GetString("Identificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Contatos.
        /// </summary>
        public static string ListaDeContatos {
            get {
                return ResourceManager.GetString("ListaDeContatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Login.
        /// </summary>
        public static string LoginInvalid {
            get {
                return ResourceManager.GetString("LoginInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string LoginInvalidEmail {
            get {
                return ResourceManager.GetString("LoginInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        public static string LoginInvalidPassword {
            get {
                return ResourceManager.GetString("LoginInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Disabled.
        /// </summary>
        public static string LoginNotEnabled {
            get {
                return ResourceManager.GetString("LoginNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro enviando mensagens..
        /// </summary>
        public static string MensagemEnviadaComErro {
            get {
                return ResourceManager.GetString("MensagemEnviadaComErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagens.
        /// </summary>
        public static string Mensagens {
            get {
                return ResourceManager.GetString("Mensagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagens Enviadas.
        /// </summary>
        public static string MensagensEnviadas {
            get {
                return ResourceManager.GetString("MensagensEnviadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagens enviadas com sucesso..
        /// </summary>
        public static string MensagensEnvidasComSucesso {
            get {
                return ResourceManager.GetString("MensagensEnvidasComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meus Contatos.
        /// </summary>
        public static string MeusContatos {
            get {
                return ResourceManager.GetString("MeusContatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados de acesso.
        /// </summary>
        public static string MeusDadosDeAcesso {
            get {
                return ResourceManager.GetString("MeusDadosDeAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meus Tickets.
        /// </summary>
        public static string MinhasDuvidas {
            get {
                return ResourceManager.GetString("MinhasDuvidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minhas Listas.
        /// </summary>
        public static string MinhasListas {
            get {
                return ResourceManager.GetString("MinhasListas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar novo Ticket.
        /// </summary>
        public static string NovaDuvida {
            get {
                return ResourceManager.GetString("NovaDuvida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NovaMensagem.
        /// </summary>
        public static string NovaMensagem {
            get {
                return ResourceManager.GetString("NovaMensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Senha.
        /// </summary>
        public static string NovaSenha {
            get {
                return ResourceManager.GetString("NovaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar Acesso.
        /// </summary>
        public static string NovoCadastro {
            get {
                return ResourceManager.GetString("NovoCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painel do Cliente.
        /// </summary>
        public static string PainelDoCliente {
            get {
                return ResourceManager.GetString("PainelDoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendente.
        /// </summary>
        public static string Pendente {
            get {
                return ResourceManager.GetString("Pendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de Contatos.
        /// </summary>
        public static string QuantidadeDeContatos {
            get {
                return ResourceManager.GetString("QuantidadeDeContatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo Cobrado.
        /// </summary>
        public static string QuantoFoiCobrado {
            get {
                return ResourceManager.GetString("QuantoFoiCobrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar Senha.
        /// </summary>
        public static string RecuperarSenha {
            get {
                return ResourceManager.GetString("RecuperarSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um email com a sua senha foi enviado para sua conta. .
        /// </summary>
        public static string RecuperouSenha {
            get {
                return ResourceManager.GetString("RecuperouSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string Remover {
            get {
                return ResourceManager.GetString("Remover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respondido.
        /// </summary>
        public static string Respondido {
            get {
                return ResourceManager.GetString("Respondido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URI of the service was not found in the applications configuration file..
        /// </summary>
        public static string RestfulServiceURINotFound {
            get {
                return ResourceManager.GetString("RestfulServiceURINotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumo de Operações.
        /// </summary>
        public static string ResumoDeOperacoes {
            get {
                return ResourceManager.GetString("ResumoDeOperacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo de Mensagens.
        /// </summary>
        public static string SaldoTotal {
            get {
                return ResourceManager.GetString("SaldoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um Contato.
        /// </summary>
        public static string SelecionarContato {
            get {
                return ResourceManager.GetString("SelecionarContato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma Lista.
        /// </summary>
        public static string SelecionarLista {
            get {
                return ResourceManager.GetString("SelecionarLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Senha {
            get {
                return ResourceManager.GetString("Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha Atual.
        /// </summary>
        public static string SenhaAtual {
            get {
                return ResourceManager.GetString("SenhaAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha atual não está correta..
        /// </summary>
        public static string SenhaAtualErrada {
            get {
                return ResourceManager.GetString("SenhaAtualErrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação de Cadastro.
        /// </summary>
        public static string SolicitacaoDeCadastro {
            get {
                return ResourceManager.GetString("SolicitacaoDeCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitações de Cadastro.
        /// </summary>
        public static string SolicitacoesDeCadastro {
            get {
                return ResourceManager.GetString("SolicitacoesDeCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string Telefone {
            get {
                return ResourceManager.GetString("Telefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto da Mensagem.
        /// </summary>
        public static string TextodaMensagem {
            get {
                return ResourceManager.GetString("TextodaMensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextoSolicitacaoDeCadastro.
        /// </summary>
        public static string TextoSolicitacaodeCadastro {
            get {
                return ResourceManager.GetString("TextoSolicitacaodeCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do Ticket.
        /// </summary>
        public static string Ticket {
            get {
                return ResourceManager.GetString("Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        public static string Tickets {
            get {
                return ResourceManager.GetString("Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de Mensagens Enviadas.
        /// </summary>
        public static string TotalMsgEnviadas {
            get {
                return ResourceManager.GetString("TotalMsgEnviadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trocar Senha.
        /// </summary>
        public static string TrocarSenha {
            get {
                return ResourceManager.GetString("TrocarSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.
        /// </summary>
        public static string Ver {
            get {
                return ResourceManager.GetString("Ver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string website_Admin {
            get {
                return ResourceManager.GetString("website_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administradores.
        /// </summary>
        public static string website_Adminsitradores {
            get {
                return ResourceManager.GetString("website_Adminsitradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativar.
        /// </summary>
        public static string website_Ativar {
            get {
                return ResourceManager.GetString("website_Ativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string website_Back {
            get {
                return ResourceManager.GetString("website_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bem Vindo.
        /// </summary>
        public static string website_Bemvindo {
            get {
                return ResourceManager.GetString("website_Bemvindo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string website_Cliente {
            get {
                return ResourceManager.GetString("website_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string website_Clientes {
            get {
                return ResourceManager.GetString("website_Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o Cliente.
        /// </summary>
        public static string website_ClientId {
            get {
                return ResourceManager.GetString("website_ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato.
        /// </summary>
        public static string website_Contrato {
            get {
                return ResourceManager.GetString("website_Contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contratos.
        /// </summary>
        public static string website_Contratos {
            get {
                return ResourceManager.GetString("website_Contratos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        public static string website_Create {
            get {
                return ResourceManager.GetString("website_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envie uma mensagem SMS.
        /// </summary>
        public static string website_CreateTestMessage {
            get {
                return ResourceManager.GetString("website_CreateTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Expiração.
        /// </summary>
        public static string website_DataFinal {
            get {
                return ResourceManager.GetString("website_DataFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string website_DataInicial {
            get {
                return ResourceManager.GetString("website_DataInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desativar.
        /// </summary>
        public static string website_Desativar {
            get {
                return ResourceManager.GetString("website_Desativar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes.
        /// </summary>
        public static string website_Details {
            get {
                return ResourceManager.GetString("website_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string website_Edit {
            get {
                return ResourceManager.GetString("website_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string website_Email {
            get {
                return ResourceManager.GetString("website_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string website_Home {
            get {
                return ResourceManager.GetString("website_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        public static string website_Id {
            get {
                return ResourceManager.GetString("website_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string website_IsEnabled {
            get {
                return ResourceManager.GetString("website_IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string website_Login {
            get {
                return ResourceManager.GetString("website_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logoff.
        /// </summary>
        public static string website_Logoff {
            get {
                return ResourceManager.GetString("website_Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem.
        /// </summary>
        public static string website_Mensagem {
            get {
                return ResourceManager.GetString("website_Mensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number to send.
        /// </summary>
        public static string website_MensagemDestinatario {
            get {
                return ResourceManager.GetString("website_MensagemDestinatario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Text.
        /// </summary>
        public static string website_MensagemTexto {
            get {
                return ResourceManager.GetString("website_MensagemTexto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string website_Mensagens {
            get {
                return ResourceManager.GetString("website_Mensagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string website_Name {
            get {
                return ResourceManager.GetString("website_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string website_Password {
            get {
                return ResourceManager.GetString("website_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages Credit.
        /// </summary>
        public static string website_SaldoMensagens {
            get {
                return ResourceManager.GetString("website_SaldoMensagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string website_Submit {
            get {
                return ResourceManager.GetString("website_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sms Gateway.
        /// </summary>
        public static string website_Title {
            get {
                return ResourceManager.GetString("website_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammount Charged.
        /// </summary>
        public static string website_ValorCobrado {
            get {
                return ResourceManager.GetString("website_ValorCobrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
