// <auto-generated />
namespace SmsGateway.Infrastructure.Data.CoreContext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Tickets : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tickets));
        
        string IMigrationMetadata.Id
        {
            get { return "201303170001060_Tickets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
