// <auto-generated />
namespace SmsGateway.Infrastructure.Data.CoreContext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PacoteListaDeContato : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PacoteListaDeContato));
        
        string IMigrationMetadata.Id
        {
            get { return "201303120605322_Pacote-ListaDeContato"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
